name: 'sixthsense_proj' # profiles.yml에 정의된 프로필 이름과 일치해야 함
version: '1.0.0'
config-version: 2

profile: 'sixthsense_proj' # profiles.yml의 프로필 이름

model-paths: ["models"] # models 폴더에 모델 파일이 위치

models:
  sixthsense_proj:
    # 모든 모델에 대한 기본 설정
    +materialized: table