version: 2

sources:
  - name: raw_data
    schema: raw_data
    database: "{{ env_var('REDSHIFT_DB') }}" # Redshift DB 이름 (profiles.yml과 동일)

    tables:
      - name: daily_boxoffice
      - name: weekly_boxoffice
      - name: movie_details
